version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sci_review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sci_review
    ports:
      - "8080:8080"
