name: Go build

env:
  SERVER_URL: ${{ secrets.SERVER_URL }}
  SERVER_PATH: ${{ secrets.SERVER_PATH }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  PRIVATE_KEY_NAME: ${{ secrets.PRIVATE_KEY_NAME }}
  ENV_VARS: ${{ secrets.ENV_VARS }}
  SCRIPT: ${{ secrets.SCRIPT }}

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go get .
      
    - name: Build
      run: go build -v -o sci_review_app .

    - name: Deploy
      run: |
        echo "$PRIVATE_KEY" > ${PRIVATE_KEY_NAME}
        chmod 600 ${PRIVATE_KEY_NAME}
        ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR -i "$PRIVATE_KEY_NAME" ${SERVER_URL} "$SCRIPT develop $ENV_VARS"
